<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141221104200 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_tracking (persistence_object_identifier VARCHAR(40) NOT NULL, post VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, iphash VARCHAR(255) NOT NULL, INDEX IDX_4A9BBFB75A8A6C8D (post), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_tracking ADD CONSTRAINT FK_4A9BBFB75A8A6C8D FOREIGN KEY (post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP views");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE flowpack_snippets_domain_model_tracking");
	}
}