<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140707223042 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_comment (persistence_object_identifier VARCHAR(40) NOT NULL, post VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, author VARCHAR(80) NOT NULL, emailaddress VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, INDEX IDX_CBD3EDA55A8A6C8D (post), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_comment ADD CONSTRAINT FK_CBD3EDA55A8A6C8D FOREIGN KEY (post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE flowpack_snippets_domain_model_comment");
	}
}