<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140511135617 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_tag (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, parent VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_E4ABC46A3D8E604F (parent), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_post (persistence_object_identifier VARCHAR(40) NOT NULL, author VARCHAR(40) DEFAULT NULL, category VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, date DATETIME NOT NULL, active TINYINT(1) NOT NULL, description VARCHAR(1000) DEFAULT NULL, content LONGTEXT DEFAULT NULL, url VARCHAR(2000) DEFAULT NULL, options LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', views INT NOT NULL, rating INT NOT NULL, INDEX IDX_EFB073FDBDAFD8C8 (author), INDEX IDX_EFB073FD64C19C1 (category), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_post_tags_join (snippets_post VARCHAR(40) NOT NULL, snippets_tag VARCHAR(40) NOT NULL, INDEX IDX_65D82DFA284DC92D (snippets_post), INDEX IDX_65D82DFAC34B9245 (snippets_tag), PRIMARY KEY(snippets_post, snippets_tag)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_category ADD CONSTRAINT FK_E4ABC46A3D8E604F FOREIGN KEY (parent) REFERENCES flowpack_snippets_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD CONSTRAINT FK_EFB073FDBDAFD8C8 FOREIGN KEY (author) REFERENCES typo3_neos_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD CONSTRAINT FK_EFB073FD64C19C1 FOREIGN KEY (category) REFERENCES flowpack_snippets_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_tags_join ADD CONSTRAINT FK_65D82DFA284DC92D FOREIGN KEY (snippets_post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_tags_join ADD CONSTRAINT FK_65D82DFAC34B9245 FOREIGN KEY (snippets_tag) REFERENCES flowpack_snippets_domain_model_tag (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_tags_join DROP FOREIGN KEY FK_65D82DFAC34B9245");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_category DROP FOREIGN KEY FK_E4ABC46A3D8E604F");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP FOREIGN KEY FK_EFB073FD64C19C1");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_tags_join DROP FOREIGN KEY FK_65D82DFA284DC92D");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_tag");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_category");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_post");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_post_tags_join");
	}
}