<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140713160729 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_post_upvotes_join (snippets_post VARCHAR(40) NOT NULL, snippets_user VARCHAR(40) NOT NULL, INDEX IDX_4388257B284DC92D (snippets_post), INDEX IDX_4388257BFF5473E9 (snippets_user), PRIMARY KEY(snippets_post, snippets_user)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_post_downvotes_join (snippets_post VARCHAR(40) NOT NULL, snippets_user VARCHAR(40) NOT NULL, INDEX IDX_EB40034C284DC92D (snippets_post), INDEX IDX_EB40034CFF5473E9 (snippets_user), PRIMARY KEY(snippets_post, snippets_user)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_post_favorites_join (snippets_post VARCHAR(40) NOT NULL, snippets_user VARCHAR(40) NOT NULL, INDEX IDX_D012810E284DC92D (snippets_post), INDEX IDX_D012810EFF5473E9 (snippets_user), PRIMARY KEY(snippets_post, snippets_user)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_upvotes_join ADD CONSTRAINT FK_4388257B284DC92D FOREIGN KEY (snippets_post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_upvotes_join ADD CONSTRAINT FK_4388257BFF5473E9 FOREIGN KEY (snippets_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_downvotes_join ADD CONSTRAINT FK_EB40034C284DC92D FOREIGN KEY (snippets_post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_downvotes_join ADD CONSTRAINT FK_EB40034CFF5473E9 FOREIGN KEY (snippets_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_favorites_join ADD CONSTRAINT FK_D012810E284DC92D FOREIGN KEY (snippets_post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post_favorites_join ADD CONSTRAINT FK_D012810EFF5473E9 FOREIGN KEY (snippets_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP rating");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE flowpack_snippets_domain_model_post_upvotes_join");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_post_downvotes_join");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_post_favorites_join");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD rating INT NOT NULL");
	}
}