<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141230205207 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_event (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, post VARCHAR(40) DEFAULT NULL, timestamp DATETIME NOT NULL, type VARCHAR(255) NOT NULL, entity VARCHAR(255) DEFAULT NULL, entityidentifier VARCHAR(255) DEFAULT NULL, INDEX IDX_6B1E41848D93D649 (user), INDEX IDX_6B1E41845A8A6C8D (post), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_event ADD CONSTRAINT FK_6B1E41848D93D649 FOREIGN KEY (user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_event ADD CONSTRAINT FK_6B1E41845A8A6C8D FOREIGN KEY (post) REFERENCES flowpack_snippets_domain_model_post (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE flowpack_snippets_domain_model_event");
	}
}