<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141226115343 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_category_followers_join (snippets_category VARCHAR(40) NOT NULL, snippets_user VARCHAR(40) NOT NULL, INDEX IDX_FD33263AE24CED6 (snippets_category), INDEX IDX_FD33263FF5473E9 (snippets_user), PRIMARY KEY(snippets_category, snippets_user)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_tag_followers_join (snippets_tag VARCHAR(40) NOT NULL, snippets_user VARCHAR(40) NOT NULL, INDEX IDX_A5E3DE1DC34B9245 (snippets_tag), INDEX IDX_A5E3DE1DFF5473E9 (snippets_user), PRIMARY KEY(snippets_tag, snippets_user)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_user_followers_join (snippets_user VARCHAR(40) NOT NULL, related_user VARCHAR(40) NOT NULL, INDEX IDX_1E270155FF5473E9 (snippets_user), INDEX IDX_1E2701556681724C (related_user), PRIMARY KEY(snippets_user, related_user)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_category_followers_join ADD CONSTRAINT FK_FD33263AE24CED6 FOREIGN KEY (snippets_category) REFERENCES flowpack_snippets_domain_model_category (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_category_followers_join ADD CONSTRAINT FK_FD33263FF5473E9 FOREIGN KEY (snippets_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_tag_followers_join ADD CONSTRAINT FK_A5E3DE1DC34B9245 FOREIGN KEY (snippets_tag) REFERENCES flowpack_snippets_domain_model_tag (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_tag_followers_join ADD CONSTRAINT FK_A5E3DE1DFF5473E9 FOREIGN KEY (snippets_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_user_followers_join ADD CONSTRAINT FK_1E270155FF5473E9 FOREIGN KEY (snippets_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_user_followers_join ADD CONSTRAINT FK_1E2701556681724C FOREIGN KEY (related_user) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE flowpack_snippets_domain_model_category_followers_join");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_tag_followers_join");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_user_followers_join");
	}
}