<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140713102904 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flowpack_snippets_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_user ADD CONSTRAINT FK_38A9C93947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP FOREIGN KEY FK_EFB073FDBDAFD8C8");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD CONSTRAINT FK_EFB073FDBDAFD8C8 FOREIGN KEY (author) REFERENCES flowpack_snippets_domain_model_user (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP FOREIGN KEY FK_EFB073FDBDAFD8C8");
		$this->addSql("DROP TABLE flowpack_snippets_domain_model_user");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP FOREIGN KEY FK_EFB073FDBDAFD8C8");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD CONSTRAINT FK_EFB073FDBDAFD8C8 FOREIGN KEY (author) REFERENCES typo3_neos_domain_model_user (persistence_object_identifier)");
	}
}