<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150109205311 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD capture VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post ADD CONSTRAINT FK_EFB073FD8BFEA6E5 FOREIGN KEY (capture) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_EFB073FD8BFEA6E5 ON flowpack_snippets_domain_model_post (capture)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP FOREIGN KEY FK_EFB073FD8BFEA6E5");
		$this->addSql("DROP INDEX IDX_EFB073FD8BFEA6E5 ON flowpack_snippets_domain_model_post");
		$this->addSql("ALTER TABLE flowpack_snippets_domain_model_post DROP capture");
	}
}