#                                                                        #
# subroutes configuration for the Flowpack Snippets package              #
#                                                                        #

-
  name: 'Single Post Search Show'
  uriPattern: '{node}/{--flowpack_snippets-search.post}.html'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-search':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Post'
      '@action': 'show'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
    '--flowpack_snippets-search.post':
      objectType: '\Flowpack\Snippets\Domain\Model\Post'
      uriPattern: '{date:Y}/{date:m}/{date:d}/{title}'
  appendExceedingArguments: TRUE

-
  name: 'Single Post Teaser Show'
  uriPattern: '{node}/{--flowpack_snippets-teaser.post}.html'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-teaser':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Post'
      '@action': 'show'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
    '--flowpack_snippets-teaser.post':
      objectType: '\Flowpack\Snippets\Domain\Model\Post'
      uriPattern: '{date:Y}/{date:m}/{date:d}/{title}'
  appendExceedingArguments: TRUE

-
  name: 'Single Post Search Edit'
  uriPattern: '{node}/edit/{--flowpack_snippets-search.post}.html'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-search':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Post'
      '@action': 'edit'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
    '--flowpack_snippets-search.post':
      objectType: '\Flowpack\Snippets\Domain\Model\Post'
      uriPattern: '{date:Y}/{date:m}/{date:d}/{title}'
  appendExceedingArguments: TRUE

-
  name: 'Categories'
  uriPattern: '{node}/category/{--flowpack_snippets-search.category}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-search':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Search'
      '@action': 'search'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Tag'
  uriPattern: '{node}/tag/{--flowpack_snippets-search.tag}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-search':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Search'
      '@action': 'search'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'cloud Tag'
  uriPattern: '{node}/tag/{--flowpack_snippets-teaser.tag}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-teaser':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Search'
      '@action': 'search'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Author'
  uriPattern: '{node}/author/{--flowpack_snippets-search.author}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--flowpack_snippets-search':
      '@package': 'Flowpack.Snippets'
      '@controller': 'Search'
      '@action': 'search'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Post Action for Ajax Usage'
  uriPattern: 'Post/{@action}'
  defaults:
    @package: 'Flowpack.Snippets'
    @controller: 'Post'
  routeParts:
    'post':
      objectType: '\Flowpack\Snippets\Domain\Model\Post'