TYPO3:
  Flow:
    object:
      excludeClasses:
        'fabpot.*' : ['.*']
        'embed.*' : ['.*']
        'ruflin.*' : ['.*']
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              Flowpack\Snippets\Security\NeosRequestPattern: 'backend'
          FrontendProvider:
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              Flowpack\Snippets\Security\NeosRequestPattern: 'frontend'

  Neos:
    typoScript:
      autoInclude:
          # auto-include "Private/Resources/TypoScript/Root.ts2" from this package!
        'Flowpack.Snippets': TRUE

    modules:
      snippets:
        label: Snippets
        controller: \Flowpack\Snippets\Controller\Module\SnippetsController
        description: 'Manage Snippets'
        icon: icon-code
        resource: 'Flowpack_Snippets_Backend_Module_Snippets'
        submodules:
          posts:
            label: Post
            controller: \Flowpack\Snippets\Controller\Module\Snippets\PostsController
            description: 'Manage Posts'
            icon: icon-file
            resource: 'Flowpack_Snippets_Backend_Module_Snippets_Posts'
            widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
            actions:
              index:
                label: 'Manage Posts'
                title: 'Manage Posts'
          categories:
            label: Category
            controller: \Flowpack\Snippets\Controller\Module\Snippets\CategoriesController
            description: 'Manage Categories'
            icon: icon-folder-open
            resource: 'Flowpack_Snippets_Backend_Module_Snippets_Categories'
            widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
            actions:
              index:
                label: 'Manage Categories'
                title: 'Manage Categories'
          tags:
            label: Tag
            controller: \Flowpack\Snippets\Controller\Module\Snippets\TagsController
            description: 'Manage Tags'
            icon: icon-tags
            resource: 'Flowpack_Snippets_Backend_Module_Snippets_Tags'
            widgetTemplatePathAndFileName: 'resource://TYPO3.Neos/Private/Templates/Module/Widget.html'
            actions:
              index:
                label: 'Manage Tags'
                title: 'Manage Tags'

Flowpack:
  ElasticSearch:
    realtimeIndexing:
      enabled: FALSE

  Snippets:
    editorButtons:
      -
        - name: bold
          title: Bold - Ctrl+B
          icon: fa fa-bold
          active: TRUE
        - name: italic
          title: Italic - Ctrl+I
          icon: fa fa-italic
          active: TRUE
      -
        - name: link
          title: Link - Ctrl+L
          icon: fa fa-link
          active: TRUE
        - name: image
          title: Image - Ctrl+G
          icon: fa fa-picture-o
          active: TRUE
        - name: quote
          title: Blockquote - Ctrl+Q
          icon: fa fa-quote-right
          active: TRUE
        - name: code
          title: Code Sample - Ctrl+K
          icon: fa fa-code
          active: TRUE
      -
        - name: olist
          title: Numbered List <ol> Ctrl+O
          icon: fa fa-list-ol
          active: TRUE
        - name: ulist
          title: Bulleted List <ul> Ctrl+U
          icon: fa fa-list-ul
          active: TRUE
        - name: heading
          title: Heading <h1>/<h2> Ctrl+H
          icon: fa fa-header
          active: TRUE
        - name: hr
          title: Horizontal Rule <hr> Ctrl+R
          icon: fa fa-ellipsis-h
          active: TRUE
      -
        - name: undo
          title: Undo - Ctrl+Z
          icon: fa fa-undo
          active: TRUE
        - name: redo
          title: Redo - Ctrl+Y
          icon: fa fa-repeat
          active: TRUE
    embed:
      provider:
        'OEmbed': TRUE
        'OpenGraph': TRUE
        'TwitterCards': FALSE
        'Facebook': FALSE
        'Html': FALSE
    elasticSearch:
      client:
        scheme: http
        host: localhost
        port: 9200
      index: snippets
      type: post
      hitsPerPage: 20
      maximumNumberOfPages: 10
      filteredQuery: TRUE
      facets: [category, tags, type, providerName]
    notification:
      post:
        recipientAddress:
        recipientName:
        senderAddress:
        senderName:
        templatePathAndFilename: resource://Flowpack.Snippets/Private/Templates/Post/PostNotification.txt
        format: text/plain
      comment:
        recipientAddress:
        recipientName:
        senderAddress:
        senderName:
        templatePathAndFilename: resource://Flowpack.Snippets/Private/Templates/Post/CommentNotification.txt
        format: text/plain